config/routes.rb
Demerits::Application.routes.draw do
  get '/auth/:provider/callback' => 'authentications#create'
  get 'login' => 'authentications#index'

  resources :authentications, only: %i[index create destroy]
  resources :users

  concern :votable do
    resource :vote, only: %i[show create update destroy]
  end

  resources :victims, concerns: :votable

  root 'victims#index'

end

app/models/victim.rb
class Victim < ActiveRecord::Base
  acts_as_votable
end

app/controllers/victims_controller.rb
class VictimsController < ApplicationController
  before_action :set_victim, only: [:show, :edit, :update, :destroy]

  # GET /victims
  # GET /victims.json
  def index
    @victims = Victim.all
  end

  # GET /victims/1
  # GET /victims/1.json
  def show
  end

  # GET /victims/new
  def new
    @victim = Victim.new
  end

  # GET /victims/1/edit
  def edit
  end

  # POST /victims
  # POST /victims.json
  def create
    @victim = Victim.new(victim_params)

    respond_to do |format|
      if @victim.save
        format.html { redirect_to @victim, notice: 'Victim was successfully created.' }
        format.json { render action: 'show', status: :created, location: @victim }
      else
        format.html { render action: 'new' }
        format.json { render json: @victim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /victims/1
  # PATCH/PUT /victims/1.json
  def update
    respond_to do |format|
      if @victim.update(victim_params)
        format.html { redirect_to @victim, notice: 'Victim was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @victim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /victims/1
  # DELETE /victims/1.json
  def destroy
    @victim.destroy
    respond_to do |format|
      format.html { redirect_to victims_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_victim
      @victim = Victim.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def victim_params
      params.require(:victim).permit(:name, :image)
    end
end

app/helpers/victims_helper.rb
module VictimsHelper
end

app/views/victims/_form.html.haml
= form_for @victim do |f|
  - if @victim.errors.any?
    #error_explanation
      %h2= "#{pluralize(@victim.errors.count, "error")} prohibited this victim from being saved:"
      %ul
        - @victim.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name

  .field
    = f.label :image
    = f.text_field :image

  .actions
    = f.submit 'Save'

app/views/victims/edit.html.haml
%h1 Editing victim

= render 'form'

= link_to 'Show', @victim
\|
= link_to 'Back', victims_path

app/views/victims/index.html.haml
.large-8.columns
  %h1
    = t 'victim.index_heading'
  %table
    %thead
      %tr
        %th Name
        %th
    %tbody
      - @victims.each do |victim|
        %tr
          %td.victim-link
            = link_to victim.name, victim
          %td
            = link_to 'Edit', edit_victim_path(victim)
            |
            = link_to 'Destroy', victim, :method => :delete, :data => { :confirm => 'Are you sure?' }

.large-4.columns
  = link_to 'New Victim', new_victim_path

app/views/victims/new.html.haml
.large-8.columns
  %h1 New
  = render 'form'
  = link_to 'Back', victims_path
.large-4.columns

app/views/victims/show.html.erb
<div id="notice">
  <%= notice %>
</div>
<div ng-controller="DemeritCtrl">
  <div class="z-top">
    <h1 class="large-heading victim-title" ng-bind='victim.name'></h1>
  </div>
  <div class="demerit-target">
    <div class="target-image" style="background-image: url('<%= @victim.image %>')"></div>
    <div class="target-overlay" ng-click="addDemerit()">
      <%= image_tag 'down-arrow.svg', height: '100%', width: '100%' %>
    </div>
    <div ng-click="removeDemerit()">
      <%= image_tag 'up-circle.svg', class: 'remove-demerit' %>
    </div>
  </div>


  <div class="footer">
    <div class="demerit-count-heading">
      <%= image_tag 'down-circle.svg', height: 16, width: 16 %>
      de<strong>MERIT Count:</strong>
    </div>
    <div ng-bind='victim.tally' class="demerit-count"></div>
  </div>
</div>