config/routes.rb
Demerits::Application.routes.draw do
  get '/auth/:provider/callback' => 'authentications#create'
  get 'login' => 'authentications#index'

  resources :authentications, only: %i[index create destroy]
  resources :users

  concern :votable do
    resource :vote, only: %i[show create update destroy]
  end

  resources :victims, concerns: :votable

  root 'victims#index'

end

app/models/authentication/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user

  validates :uid, uniqueness: { scope: :provider }

  PROVIDERS = %w(twitter facebook)

  def provider_name
    provider.titleize
  end

  def dsl
    raise 'This method should be overriden in subclass'
  end
end

app/models/authentication/facebook_authentication.rb
class FacebookAuthentication < Authentication
  def dsl
    proc do
      traverse :info do
        defaults :name, :email, :image
      end
    end
  end
end

app/models/authentication/twitter_authentication.rb
class TwitterAuthentication < Authentication
  def dsl
    proc do
      traverse :info do
        defaults :name, :image
      end
    end
  end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def index
    @authentications = current_user.authentications if current_user
  end

  def create
    omniauth = request.env['omniauth.auth']
    authentication = Authentication.find_by omniauth.slice(:provider, :uid)
    if authentication
      flash[:notice] = 'Signed in successfully.'
      login(authentication.user)
    elsif current_user
      current_user.create_authentication omniauth
      flash[:notice] = 'Authentication successful.'
      redirect_to root_path
    else
      user = User.new
      user.apply_omniauth(omniauth)
      if user.save
        flash[:notice] = 'Signed in successfully.'
        login(user)
      end
    end
  end

  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = 'Successfully destroyed authentication.'
    redirect_to login_path
  end

  private

  def login(user)
    UserSession.create(user)
    redirect_to root_path
  end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/views/authentications/create.html.haml
%h1 OmniAuthProviders#create
%p Find me in app/views/omni_auth_providers/create.html.haml

app/views/authentications/destroy.html.haml
%h1 OmniAuthProviders#destroy
%p Find me in app/views/omni_auth_providers/destroy.html.haml

app/views/authentications/index.html.haml
- content_for :title do
  Sign In Options

- if @authentications
  - unless @authentications.empty?
    %p
      %strong You have signed in with these services:

    .authentications
      - @authentications.each do |authentication|
        .authentication
          = image_tag "authentications/#{authentication.provider}_32.png", size: '32x32'
          .provider= authentication.provider_name
          .uid= authentication.uid
          = link_to 'X', authentication_path(authentication), confirm: 'Are you sure you want to remove this authentication option?', method: :delete, class: 'remove'
      .clear
  %p
    %strong Add another service to sign in with:
- else
  %p
    %strong Sign in through one of these services:

- Authentication::PROVIDERS.each do |provider|
  = link_to "/auth/#{provider}", class: 'auth_provider' do
    = image_tag "authentications/#{provider}_64.png", alt: provider.titleize
    = provider.titleize

.clear